name: Release
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build On:(${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      TZ: Asia/Shanghai
    permissions:
      contents: write
      security-events: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: jadehh/onetv-android
          ref: next
          path: onetv-android

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          cd mytv-android
          bash gradlew assembleDebug
      - name: Get Commit Messages
        id: get_git_latest_message
        run: |
          cd mytv-android
          message=$(git log -1 --format=%B HEAD)
          echo "Latest Message is ${message}"
          echo ::set-output name=git_latest::$message
      - name: Get Current Time
        id: get_current_time
        run: |
          current_time=$(date +%F%t%T)
          echo "current_time is ${current_time}"
          echo ::set-output name=current_time::$current_time
      - name: Generate Changelog
        run: |
          cd mytv-android
          echo "# ${{ github.ref_name }}" > ${{ github.workspace }}-CHANGELOG.txt
          echo "${{steps.get_current_time.outputs.current_time}}"
          echo "## ${{steps.get_current_time.outputs.current_time}} ${{ github.ref_name }}" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "### Open Version Update" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "* ${{steps.get_git_latest_message.outputs.git_latest}}" >> ${{ github.workspace }}-CHANGELOG.txt
      - name: Deploy
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: ./onetv-android/tv/build/outputs/apk/debug/*.apk
        env:
          GITHUB_TOKEN: ${{ github.token }} # 给最高的权限